spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hackathon}
    username: ${DATABASE_USERNAME:hackathon}
    password: ${DATABASE_PASSWORD:root}
  flyway:
    enabled: true
  # JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: update

management:
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: "true"
    defaults:
      enabled: "true"

openai:
  api-key: ${OPENAI_KEY}
